config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :listeners, :controllers => { :registrations => "registrations" }

  devise_for :speakers
  resources :speakers, only: [:show]

  resources :messages do
    resources :messageparts
  end

  root 'pages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :speaker
  has_many :messageparts, dependent: :destroy
  has_attached_file :image, styles: { large: "500x500", medium: "300x350#" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_presence_of :send_at

  #returns the message which needs to be process today
  scope :todays_messages, -> { where("(DATE(send_at) = ? OR DATE(send_at) = ?) AND delivered_at IS ?", Date.today, 1.day.from_now.to_date, nil) }

  #returns messages who have messageparts for sending email
  scope :messages_to_mail, -> { where("id IN (?) and delivered_at IS NOT ?", Messagepart.message_ids_having_un_delivered_messageparts, nil) }

  #this will give listeners for message object
  #ref: http://apidock.com/rails/Module/delegate
  delegate :listeners, to: :speaker

  #class methods at one place
  class << self
    def send_messages_to_listeners
      Rails.logger.info "######send_messages_to_listeners START"

      messages = Message.todays_messages

      messages.each do |message|
        message.listeners.each do |listener|

          next unless message.valid_listener?(listener)

          send_at = send_at_for(message.send_at, listener)
          SendMessageEmailWorker.perform_at(send_at, message.id, listener.id)
        end
        message.update_attributes(delivered_at: Time.now)
      end

      Rails.logger.info "######send_messages_to_listeners END"
    end

    #get the date of sending email, by including listener's profile time(hour) and timezone
    def send_at_for send_at, listener
      DateTime.new(send_at.year, send_at.month, send_at.day, listener.recieve_message_at.to_i, 0, 0).change(:offset => listener.time_zone).utc rescue send_at
    end
  end

  #
  def valid_listener? listener
    ls = listener.listeners_speakers.where(speaker_id: speaker.id).first
    ls.created_at < created_at if ls
  end

  #default date for message should be next date.
  def default_date
    Date.today + 1.day
  end

  #default date for message_part should be next date of last message-part OR next date of message if there are no message-parts present.
  def message_part_default_date
    if messageparts.exists?
      messageparts.order(created_at: :desc).first.send_at + 1.day
    else
      send_at + 1.day
    end
  end

  #image url
  def attached_img
    image? ? image.url(:medium) : ''
  end

  def image?
    image.present?
  end

  def msg_part_no
    messageparts.count + 1
  end

  #to get the image path, used for image atachment in email.
  def get_image_path
    Rails.root.join("public").to_s + image.url(:large).split('?').first
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_speaker!, except: [:index, :show]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show

  end

  def new
    @message = current_speaker.messages.build

  end

  def create
    @message = current_speaker.messages.build(message_params)
    if @message.save
    redirect_to messages_path
  else
    render 'new'
  end
    #what user will enter in form will be message_params
  end

  def edit

  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end


  private
    def message_params
      params.require(:message).permit(:title, :description, :content, :send_at, :image)
    end

    def find_message
      @message = Message.find(params[:id])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<script type="text/javascript">
  var loadFile = function(event) {
    var elms = document.getElementById("image");
    image.innerHTML = "<div id='image'> Preview Image <img id='output' height='150' width='250' alt='Image Preview' style='margin-bottom: 10px; margin-top: 15px;'/><br>"
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

<%= simple_form_for @message, html: { multipart: true }  do |f| %>
  <%= f.input :title, label: "Message Title"  %>
  <%= f.input :description, label: "Short Description" %>
  <%= f.input :content, :as => :text, :input_html => { 'rows' => 10} %>
  <strong>Category:</strong>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  <%= f.file_field :picture, onchange: "loadFile(event)" %>

  <div id="image"></div>

  <%= f.button :submit %>

<% end %>

<% if @message.picture_url %>
<%= link_to "Delete Image", "/message/delete/"+@message.id.to_s %>
<% end %>

app/views/messages/_index.html.erb
<% @messages.each do |message| %>
<!-- <div><%= gravatar_for message.speaker, size: 100 %>
<h3>Speaker Name: <%= message.speaker.name %></h3>
</div> -->
  <div class="col-md-4">
    <div class="message">
      <h2 class="message-title"> <%= message.title %> </h2>
      <%= link_to "View Message", message_path(message), class: "btn btn-default" %>
      <p><%= render message.categories %></p>
    </div>

  </div>

<% end %>

app/views/messages/edit.html.erb
<script type="text/javascript">
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

<h1>Edit Message</h1>
<%= render 'form' %>

<% if @message.picture_url %>
Current Image
  <%= image_tag @message.picture_url, width: "250", height: "150" %>
<% end %>

app/views/messages/index.html.erb
<p><%= render partial: "messages/index" %></p>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>Create New Message</h2>
  <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
    <h2><%= @message.title %></h2>
    <p class="message-posted-by">Posted by <%= @message.speaker.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
    <p class="message-desc"><%= @message.description %></p>
    <p class="message-desc"><%= @message.content %></p>
    <p class="message-desc">Send at: <%= @message.send_at.strftime("%d/%m/%Y") %></p>
    <p class="message-desc"><%= image_tag @message.attached_img, size: "100x100" if @message.image? %></p>

    <h3 class="reply-to-msg">Content Parts:</h3>
    <%= render @message.messageparts %>
    <!-- Add conditional so taht the edit and destory links only apear for th user how created -->
    <div class="links btn-group">
      <%= link_to "Back", messages_path, class: "btn btn-default" %><br>
      <% if speaker_signed_in? %>

        <% if @message.speaker_id == current_speaker.id %>
          <h3>Add More Content Parts</h3>

          <%= render 'messageparts/form' %>
          <%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
          <%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>