config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :listeners, :controllers => { :registrations => "registrations" }

  devise_for :speakers
  resources :speakers, only: [:show]

  resources :messages do
    resources :messageparts
  end

  root 'pages#home'

end

app/models/messagepart.rb
class Messagepart < ActiveRecord::Base
  belongs_to :message
  belongs_to :speaker
  has_attached_file :image, styles: { large: "500x500", medium: "300x350#" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  #only un_delivered message-parts
  scope :un_delivered, -> { where("delivered_at IS ?", nil) }

  # gives the messagepart which has to mail today, for all message_id(s) returned by the above scope
  scope :message_parts_to_mail, -> { where("(DATE(send_at) = ? OR DATE(send_at) = ?) AND delivered_at IS ?", Date.today, 1.day.from_now.to_date, nil).order(:part_no) }

  # after_save :send_notification_mails_to_listners


  # def send_notification_mails_to_listners
  #     speaker.listeners.each do |l|

  #     end
  # end

  class << self

    #returns message ids of those messages who is having any un delivered messageparts
    def message_ids_having_un_delivered_messageparts
      self.un_delivered.distinct.pluck(:message_id)
    end

    #this is to schedule the message-part email to listeners based on there timezone and time(from listeners profile)
    def send_message_parts_to_listeners
      Rails.logger.info "######send_message_parts_to_listeners START"
      messages = Message.messages_to_mail

      messages.each do |message|
        messageparts = message.messageparts.message_parts_to_mail

        messageparts.each do |messagepart|
          message.listeners.each do |listener|

            next unless message.valid_listener?(listener)

            send_at = Message.send_at_for messagepart.send_at, listener
            SendMessagePartEmailWorker.perform_at(send_at, messagepart.id, listener.id)
          end

          messagepart.update_attributes(delivered_at: Time.now)
        end
      end
      Rails.logger.info "######send_message_parts_to_listeners END"
    end
  end

  def attached_img
    image? ? image.url(:medium) : ""
  end

  def image?
    image.present?
  end

  #to get the image path, used for image atachment in email.
  def get_image_path
    Rails.root.join("public").to_s + image.url(:large).split('?').first
  end
end

app/controllers/messageparts_controller.rb
class MessagepartsController < ApplicationController
  before_action :find_message
  before_action :find_messagepart, only: [:edit, :update, :destroy]
  # before_action :authenticate_speaker!, except: [:index, :show]
  before_action :authenticate_speaker!

  def create
    # @message = Message.find(params[:message_id])
    @messagepart = @message.messageparts.create(messagepart_params)
    @messagepart.speaker_id = current_speaker.id

    if @messagepart.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
    # @message = Message.find(params[:message_id])
    # @messagepart = @message.messageparts.find(params[:id])
  end

  def update
    if @messagepart.update(messagepart_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end

  end

  def destroy
    @messagepart.destroy
    redirect_to message_path(@message)


  end

  private
    def messagepart_params

      params.require(:messagepart).permit(:contentparttitle, :contentpart, :picturepart)

    end

    def find_message
      @message = Message.find(params[:message_id])

    end

    def find_messagepart
      @messagepart = @message.messageparts.find(params[:id])

    end


end

app/helpers/messageparts_helper.rb
module MessagepartsHelper
end

app/views/messageparts/_form.html.erb
<script type="text/javascript">
  var loadFile = function(event) {
    var elms = document.getElementById("image");
    image.innerHTML = "<div id='image'> Preview Image <img id='output' height='150' width='250' alt='Image Preview' style='margin-bottom: 10px; margin-top: 15px;'/><br>"
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

<%= simple_form_for([@message, @message.messageparts.build], html: { multipart: true } ) do |f| %>

<%= f.input :contentparttitle, label: "Part Title" %>
<%= f.input :contentpart, label: "Content Part", :as => :text, input_html: { :rows => 10, :class => "span6" } %>
<%= f.file_field :picturepart, onchange: "loadFile(event)" %>

<%= f.hidden_field :picturepart_cache %>


<%= f.button :submit, label: "Add Parts", :class => 'btn-custom' %>


<% end %>

app/views/messageparts/_messagepart.html.erb
<div class="comment">
  <p class="comment-content"><%= messagepart.contentparttitle %></p>
  <p class="comment-content"><%= messagepart.contentpart %></p>
    <p>
    <%= image_tag(messagepart.picturepart.url, size: "250x150", class: "gravatar") if messagepart.picturepart? %>
    </p>

    <div class="links">
      <% if speaker_signed_in? %>
        <% if messagepart.speaker_id == current_speaker.id %>

          <%= link_to "Edit", edit_message_messagepart_path(messagepart.message, messagepart) %>
          <%= link_to "Delete", message_messagepart_path(messagepart.message, messagepart), method: :delete, data: { confirm: "Are you sure?" } %>
          <!-- # first argument /messagepart.message gets /messageparts3
          # messagepart gets /messagepart/1
           -->
        <% end %>
      <% end %>
    </div>
</div>

app/views/messageparts/edit.html.erb
<script type="text/javascript">
  var loadFile = function(event) {
    var elms = document.getElementById("image");
    image.innerHTML = "<div id='image'> Preview Image <img id='output' height='150' width='250' alt='Image Preview' style='margin-bottom: 10px; margin-top: 15px;'/><br>"
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

<h1>Edit Content Part</h1>
<%= simple_form_for([@message, @messagepart], html: { multipart: true } ) do |f| %>
<%= f.input :contentparttitle, label: "Title" %>
<%= f.input :contentpart, label: "Content Part", :as => :text, :input_html => { 'rows' => 10} %>
<%= f.file_field :picturepart, onchange: "loadFile(event)" %>
<%= f.hidden_field :picturepart_cache %>


 <%= f.button :submit %>
<% end %>
<% if @messagepart.picturepart_url %>
<%= image_tag @messagepart.picturepart_url, size: "250x150" %>
<%= link_to "delete Image", "/messagepart/delete/"+@messagepart.id.to_s %>
<% end %>