config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :listeners, :controllers => { :registrations => "registrations" }

  devise_for :speakers
  resources :speakers, only: [:show]

  resources :messages do
    resources :messageparts
  end

  root 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Message Follower</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <% if speaker_signed_in? %>
      <%= link_to "Message Follower", messages_path, class: "navbar-brand" %>
      <% else %>
      <%= link_to "Message Follower", root_path, class: "navbar-brand" %>
      <% end %>
</div>
    <% if speaker_signed_in? %>
      <button type="button" class="btn btn-secondary" >
        <%= link_to "New Message", new_message_path %>
      </button>
    <% end %>

    <ul class="navbar-link">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>
          Category <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li> <%= link_to category.name, category_path(category) %></li>
            <% end %>
            <% if speaker_signed_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to(new_category_path) do %>
                  New Category
                <% end %>
              </li>

            <% end %>
          </ul>
      </li>
    </ul>



<!--  top navigation-->



<div class="btn-group pull-right">
  <button type="button" class="btn btn-default  dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Listener <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">

    <% if listener_signed_in? %>
      <li><%= link_to "Edit Account", edit_listener_registration_path %></li>
      <li><%= link_to "Sign out", destroy_listener_session_path,  :method => :delete %></li>
      <% else %>
      <li><%= link_to "Log In", new_listener_session_path %></li>
      <li><%= link_to "Sign Up", new_listener_registration_path %></li>
    <% end %>

  </ul>
</div>
<div class="btn-group pull-right">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Speaker <span class="caret"></span>
  </button>


  <ul class="dropdown-menu">
    <% if speaker_signed_in? %>
      <li><%= link_to "View Profile", speaker_path(current_speaker) %></li>
      <li><%= link_to "Edit Account", edit_speaker_registration_path %></li>
      <li><%= link_to "Sign out", destroy_speaker_session_path,  :method => :delete %></li>
    <% else %>
      <li><%= link_to "Log In", new_speaker_session_path %></li>
      <li><%= link_to "Sign Up", new_speaker_registration_path %></li>
    <% end %>
  </ul>
</div>



</div>


</div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="container">

<%= yield %>

</div>
</body>
</html>